---
# see: https://github.com/bitnami/charts/blob/main/bitnami/wordpress/values.yaml
wordpressPassword: password

persistence:
  storageClass: csi-hostpath-sc
  size: 2Gi
volumePermissions:
  enabled: true

mariadb:
  primary:
    persistence:
      storageClass: csi-hostpath-sc
      size: 1Gi
