---
vcluster-k0s:
  vcluster:
    image: k0sproject/k0s:v1.28.2-k0s.0

  syncer:
    extraArgs:
      - --tls-san=10.200.200.10,35.214.232.27
      - --mount-physical-host-paths=true

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"

  sync:
    ingresses:
      enabled: true
    persistentvolumes:
      enabled: true
    storageclasses:
      enabled: true

  storage:
    className: openebs-hostpath
    size: 1Gi

  proxy:
    metricsServer:
      nodes:
        enabled: true
      pods:
        enabled: true

  isolation:
    enabled: true
    resourceQuota:
      enabled: false
    limitRange:
      enabled: false
    networkPolicy:
      enabled: true
